// Generated by CoffeeScript 1.10.0
var Actions, Category, Link, React, ReactRouter, Store;

React = require("react");

ReactRouter = require('react-router');

Link = ReactRouter.Link;

Store = require("../stores/Store");

Actions = require("../actions/Actions");

Category = React.createClass({
  render: function() {
    return (
        <div className="app">
          <Link to="/">Go main</Link>
          ZE nome
        </div>
    );
  }
});

module.exports = Category;
