// Generated by CoffeeScript 1.10.0
var Actions, Link, Main, React, ReactRouter, Store;

React = require("react");

ReactRouter = require('react-router');

Link = ReactRouter.Link;

Store = require("../stores/Store");

Actions = require("../actions/Actions");

Main = React.createClass({
  getInitialState: function() {
    return {
      countClick: Store.getCountClick()
    };
  },
  handleClick: function(ev) {
    return Actions.clickOnBtn(++this.state.countClick);
  },
  newState: function() {
    return this.setState({
      countClick: Store.getCountClick()
    });
  },
  componentWillMount: function() {
    return Store.addChangeListener(this.newState);
  },
  render: function() {
    return (
      <div className="app">
        <span>{this.state.countClick}</span>
        <button onClick={this.handleClick}>click me</button>
        <div>
          <Link to="/category">Go to category</Link>
        </div>
      </div>
    );
  }
});

module.exports = Main;
