// Generated by CoffeeScript 1.10.0
var Main, React;

React = require("react");

Main = React.createClass({
  
  render: function() {
    return (
      <div className="app">
        hello react
      </div>
    );
  }
});

module.exports = Main;
