// Generated by CoffeeScript 1.10.0
var Actions, Dispatcher, _;

Dispatcher = require('../dispatcher/Dispatcher');

_ = require("lodash");

Actions = {
  clickOnBtn: function(value) {
    return Dispatcher.handleViewAction({
      actionType: "clickOnBtn",
      data: value
    });
  }
};

module.exports = Actions;
