// Generated by CoffeeScript 1.10.0
var Dispatcher;

Dispatcher = require("flux").Dispatcher;

Dispatcher.prototype.handleViewAction = function(action) {
  return this.dispatch({
    source: 'VIEW_ACTION',
    action: action
  });
};

Dispatcher.prototype.handleServerAction = function(action) {
  return this.dispatch({
    source: 'SERVER_ACTION',
    action: action
  });
};

module.exports = new Dispatcher();
